# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ngeor.com
author: Nikolaos Georgiou
description: >- # this means to ignore newlines until "baseurl:"
  A blog by Nikolaos Georgiou
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ngeor
github_username:  ngeor
linkedin_username:  nikolaosgeorgiou
so_link: https://stackoverflow.com/users/153258/nikolaos-georgiou
rss: RSS

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: /:year/:month/:day/:title:output_ext
show_excerpts: true
google_analytics: UA-126249544-1

collections:
  category:
    output: true
  series:
    output: true
  tag:
    output: true
  wiki:
    output: true

paginate: 10
paginate_path: "/page:num/"

# used by preprocessor.py
categories:
  automation:
    description: Never send a human do a machine's job.
  consistency:
    description: |
      The codebase should look as if it were written by a single person.
      Linting, code formatting, code style, custom validations, style guides, etc.
  continuous-delivery:
    description: Continuous integration, delivery pipelines, custom tooling.
  notes:
    description: Notes, thoughts, opinions, etc.
  testing:
    description: Unit tests, integration tests, code coverage, etc.
  versioning:
    description: Semantic versioning, automatic creation of git tags, version strategies, etc.
  personal:
    hidden: true
  my-computer:
    hidden: true
  funny:
    hidden: true
